# ============================================================================
# dc3_runtime_sources.cmake  —  GENERATED, do not hand-edit.
#
# The Milo core runtime (utl/, obj/, math/, rndobj/, os/, synth/, char/, ...)
# plus the per-decomp native glue that EnsureEngineInit() needs has NOT yet
# been factored into libmilo-engine.a (Phase 0.2 is incomplete — only the
# gfx/audio/platform/char half lives in the engine today). The convergence
# tests therefore link libmilo-engine.a PLUS this set of dc3-decomp matched-
# fork + native-glue .cpp files, compiled read-only from the dc3 checkout.
#
# This list is the exact source set dc3-decomp/native's own 'milo-tests'
# target compiles (extracted from its configured build), minus the engine-
# moved files (already absent there) and minus the test .cpp themselves.
# As Phase 0.2 moves utl/obj/math/etc. into the engine, shrink this list.
#
# DC3_RUNTIME_ROOT must point at the dc3-decomp checkout root.
# ============================================================================

set(DC3_RUNTIME_SOURCES
    ${DC3_RUNTIME_ROOT}/src/App.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/game/BustAMovePanel.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/game/Game.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/game/GameMode.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/game/GamePanel.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/game/HamUser.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/game/HamUserMgr.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/game/LiveInput.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/game/PartyModeMgr.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/game/PresenceMgr.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/game/Shuttle.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/game/SongDB.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/game/SongSequence.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/AccomplishmentCampaignConditional.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/AccomplishmentCategory.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/AccomplishmentCharacterListConditional.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/AccomplishmentConditional.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/AccomplishmentCountConditional.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/Accomplishment.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/AccomplishmentDiscSongConditional.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/AccomplishmentGroup.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/AccomplishmentManager.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/AccomplishmentOneShot.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/AccomplishmentProgress.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/AccomplishmentSongConditional.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/AccomplishmentSongListConditional.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/AppLabel.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/AppMiniLeaderboardDisplay.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/AppNavProvider.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/Award.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/BlacklightPanel.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/CalibrationPanel.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/Campaign.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/CampaignDiffSelectPanel.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/CampaignEra.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/CampaignMasterQuestCrewSelectPanel.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/CampaignMasterQuestSongSelectPanel.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/CampaignPerformer.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/CampaignProgress.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/CampaignSongSelectPanel.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/ChallengeRecord.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/ChallengeResultPanel.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/Challenges.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/ChallengeSortByScore.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/ChallengeSort.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/ChallengeSortMgr.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/ChallengeSortNode.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/CharacterProvider.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/ChooseModeProvider.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/ChooseProfilePanel.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/ContentLoadingPanel.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/ContextChecker.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/CorrectIdentityPanel.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/CrewProvider.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/CursorPanel.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/DepthBuffer.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/DifficultyProvider.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/EventDialogPanel.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/FitnessCalorieSortByCalorie.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/FitnessCalorieSort.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/FitnessCalorieSortMgr.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/FitnessCalorieSortNode.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/FitnessGoalMgr.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/FitnessProvider.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/HamMemcardAction.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/HamPanel.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/HamProfile.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/HamScreen.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/HamSongMetadata.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/HamSongMgr.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/HamStarsDisplay.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/HamStoreFilterProvider.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/HamStoreOffer.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/HamStorePanel.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/HamStoreProvider.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/HamUI.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/HelpBarPanel.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/Instarank.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/Leaderboards.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/LetterboxPanel.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/LoadingPanel.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/LockedContentPanel.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/MainMenuPanel.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/MainMenuProvider.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/MetagameRank.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/MetagameStats.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/MetaPanel.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/MetaPerformer.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/MoveRatingHistory.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/MovieProvider.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/MQSongSortByCharacter.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/MQSongSort.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/MQSongSortMgr.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/MQSongSortNode.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/MultiUserGesturePanel.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/NavListNode.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/NavListSort.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/NavListSortMgr.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/OptionsPanel.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/OutfitProvider.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/OverlayPanel.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/Overshell.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/PassiveMessagesPanel.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/PassiveMessenger.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/Playlist.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/PlaylistSongProvider.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/PlaylistSortByTypeCmp.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/PlaylistSort.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/PlaylistSortMgr.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/PlaylistSortNode.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/PracticeChoosePanel.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/ProfileMgr.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/SaveLoadManager.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/ShellInput.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/SigninScreen.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/SingleUserCrewSelectPanel.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/SkeletonChooser.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/SkeletonIdentifier.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/SkillsAwardList.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/SongRecord.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/SongSelectPanel.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/SongSelectPlaylistCustomizePanel.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/SongSelectPlaylistPanel.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/SongSortByDiff.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/SongSortByLocation.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/SongSortBySong.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/SongSort.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/SongSortMgr.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/SongSortNode.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/SongStatusMgr.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/TexLoadPanel.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/TitleProvider.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/UIEventMgr.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/Utl.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/VenueProvider.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/VoiceControlPanel.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/VoiceInputPanel.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/meta_ham/WeightInput.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/net_ham/ChallengeSystemJobs.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/net_ham/DataMinerJobs.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/net_ham/FitnessGoalJobs.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/net_ham/FriendsListJobs.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/net_ham/HamStoreCartJobs.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/net_ham/LeaderboardJobs.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/net_ham/MotdJobs.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/net_ham/PartyModeJobs.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/net_ham/PlaylistJobs.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/net_ham/RCJobDingo.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/net_ham/RockCentral.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/net_ham/ScoreJobs.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/net_ham/TokenJobs.cpp
    ${DC3_RUNTIME_ROOT}/src/lazer/net_ham/WebLinkJobs.cpp
    ${DC3_RUNTIME_ROOT}/src/system/char/Character.cpp
    ${DC3_RUNTIME_ROOT}/src/system/char/CharacterTest.cpp
    ${DC3_RUNTIME_ROOT}/src/system/char/CharBlendBone.cpp
    ${DC3_RUNTIME_ROOT}/src/system/char/CharBone.cpp
    ${DC3_RUNTIME_ROOT}/src/system/char/CharBoneDir.cpp
    ${DC3_RUNTIME_ROOT}/src/system/char/CharBoneOffset.cpp
    ${DC3_RUNTIME_ROOT}/src/system/char/CharBonesBlender.cpp
    ${DC3_RUNTIME_ROOT}/src/system/char/CharBones.cpp
    ${DC3_RUNTIME_ROOT}/src/system/char/CharBonesMeshes.cpp
    ${DC3_RUNTIME_ROOT}/src/system/char/CharBonesSamples.cpp
    ${DC3_RUNTIME_ROOT}/src/system/char/CharBoneTwist.cpp
    ${DC3_RUNTIME_ROOT}/src/system/char/CharClip.cpp
    ${DC3_RUNTIME_ROOT}/src/system/char/CharClipDisplay.cpp
    ${DC3_RUNTIME_ROOT}/src/system/char/CharClipDriver.cpp
    ${DC3_RUNTIME_ROOT}/src/system/char/CharClipGroup.cpp
    ${DC3_RUNTIME_ROOT}/src/system/char/CharClipSet.cpp
    ${DC3_RUNTIME_ROOT}/src/system/char/CharCollide.cpp
    ${DC3_RUNTIME_ROOT}/src/system/char/Char.cpp
    ${DC3_RUNTIME_ROOT}/src/system/char/CharCuff.cpp
    ${DC3_RUNTIME_ROOT}/src/system/char/CharDriver.cpp
    ${DC3_RUNTIME_ROOT}/src/system/char/CharDriverMidi.cpp
    ${DC3_RUNTIME_ROOT}/src/system/char/CharEyeDartRuleset.cpp
    ${DC3_RUNTIME_ROOT}/src/system/char/CharEyes.cpp
    ${DC3_RUNTIME_ROOT}/src/system/char/CharFaceServo.cpp
    ${DC3_RUNTIME_ROOT}/src/system/char/CharForeTwist.cpp
    ${DC3_RUNTIME_ROOT}/src/system/char/CharGuitarString.cpp
    ${DC3_RUNTIME_ROOT}/src/system/char/CharHair.cpp
    ${DC3_RUNTIME_ROOT}/src/system/char/CharIKFingers.cpp
    ${DC3_RUNTIME_ROOT}/src/system/char/CharIKFoot.cpp
    ${DC3_RUNTIME_ROOT}/src/system/char/CharIKHand.cpp
    ${DC3_RUNTIME_ROOT}/src/system/char/CharIKHead.cpp
    ${DC3_RUNTIME_ROOT}/src/system/char/CharIKMidi.cpp
    ${DC3_RUNTIME_ROOT}/src/system/char/CharIKRod.cpp
    ${DC3_RUNTIME_ROOT}/src/system/char/CharIKScale.cpp
    ${DC3_RUNTIME_ROOT}/src/system/char/CharIKSliderMidi.cpp
    ${DC3_RUNTIME_ROOT}/src/system/char/CharInterest.cpp
    ${DC3_RUNTIME_ROOT}/src/system/char/CharLipSync.cpp
    ${DC3_RUNTIME_ROOT}/src/system/char/CharLipSyncDriver.cpp
    ${DC3_RUNTIME_ROOT}/src/system/char/CharLookAt.cpp
    ${DC3_RUNTIME_ROOT}/src/system/char/CharMeshHide.cpp
    ${DC3_RUNTIME_ROOT}/src/system/char/CharMirror.cpp
    ${DC3_RUNTIME_ROOT}/src/system/char/CharNeckTwist.cpp
    ${DC3_RUNTIME_ROOT}/src/system/char/CharPollGroup.cpp
    ${DC3_RUNTIME_ROOT}/src/system/char/CharPosConstraint.cpp
    ${DC3_RUNTIME_ROOT}/src/system/char/CharServoBone.cpp
    ${DC3_RUNTIME_ROOT}/src/system/char/CharSignalApplier.cpp
    ${DC3_RUNTIME_ROOT}/src/system/char/CharSleeve.cpp
    ${DC3_RUNTIME_ROOT}/src/system/char/CharTaskMgr.cpp
    ${DC3_RUNTIME_ROOT}/src/system/char/CharTransDraw.cpp
    ${DC3_RUNTIME_ROOT}/src/system/char/CharUpperTwist.cpp
    ${DC3_RUNTIME_ROOT}/src/system/char/CharUtl.cpp
    ${DC3_RUNTIME_ROOT}/src/system/char/CharWeightable.cpp
    ${DC3_RUNTIME_ROOT}/src/system/char/CharWeightSetter.cpp
    ${DC3_RUNTIME_ROOT}/src/system/char/ClipCollide.cpp
    ${DC3_RUNTIME_ROOT}/src/system/char/ClipDistMap.cpp
    ${DC3_RUNTIME_ROOT}/src/system/char/ClipGraphGen.cpp
    ${DC3_RUNTIME_ROOT}/src/system/char/FileMerger.cpp
    ${DC3_RUNTIME_ROOT}/src/system/char/FileMergerOrganizer.cpp
    ${DC3_RUNTIME_ROOT}/src/system/char/Waypoint.cpp
    ${DC3_RUNTIME_ROOT}/src/system/flow/DrivenPropertyEntry.cpp
    ${DC3_RUNTIME_ROOT}/src/system/flow/DrivenPropertyMathOps.cpp
    ${DC3_RUNTIME_ROOT}/src/system/flow/FlowAnimate.cpp
    ${DC3_RUNTIME_ROOT}/src/system/flow/FlowCommand.cpp
    ${DC3_RUNTIME_ROOT}/src/system/flow/Flow.cpp
    ${DC3_RUNTIME_ROOT}/src/system/flow/FlowDistance.cpp
    ${DC3_RUNTIME_ROOT}/src/system/flow/FlowEventListener.cpp
    ${DC3_RUNTIME_ROOT}/src/system/flow/FlowIf.cpp
    ${DC3_RUNTIME_ROOT}/src/system/flow/FlowLabel.cpp
    ${DC3_RUNTIME_ROOT}/src/system/flow/FlowManager.cpp
    ${DC3_RUNTIME_ROOT}/src/system/flow/FlowMultiSetProperty.cpp
    ${DC3_RUNTIME_ROOT}/src/system/flow/FlowNode.cpp
    ${DC3_RUNTIME_ROOT}/src/system/flow/FlowOnStop.cpp
    ${DC3_RUNTIME_ROOT}/src/system/flow/FlowOutPort.cpp
    ${DC3_RUNTIME_ROOT}/src/system/flow/FlowPickOne.cpp
    ${DC3_RUNTIME_ROOT}/src/system/flow/FlowPtr.cpp
    ${DC3_RUNTIME_ROOT}/src/system/flow/FlowQueueable.cpp
    ${DC3_RUNTIME_ROOT}/src/system/flow/FlowRun.cpp
    ${DC3_RUNTIME_ROOT}/src/system/flow/FlowSequence.cpp
    ${DC3_RUNTIME_ROOT}/src/system/flow/FlowSetProperty.cpp
    ${DC3_RUNTIME_ROOT}/src/system/flow/FlowSlider.cpp
    ${DC3_RUNTIME_ROOT}/src/system/flow/FlowSound.cpp
    ${DC3_RUNTIME_ROOT}/src/system/flow/FlowSwitchCase.cpp
    ${DC3_RUNTIME_ROOT}/src/system/flow/FlowSwitch.cpp
    ${DC3_RUNTIME_ROOT}/src/system/flow/FlowTimer.cpp
    ${DC3_RUNTIME_ROOT}/src/system/flow/FlowTrigger.cpp
    ${DC3_RUNTIME_ROOT}/src/system/flow/FlowValueCase.cpp
    ${DC3_RUNTIME_ROOT}/src/system/flow/FlowWhile.cpp
    ${DC3_RUNTIME_ROOT}/src/system/flow/PropertyEventListener.cpp
    ${DC3_RUNTIME_ROOT}/src/system/flow/PropertyEventProvider.cpp
    ${DC3_RUNTIME_ROOT}/src/system/gesture/ArcDetector.cpp
    ${DC3_RUNTIME_ROOT}/src/system/gesture/ArchiveSkeleton.cpp
    ${DC3_RUNTIME_ROOT}/src/system/gesture/BaseSkeleton.cpp
    ${DC3_RUNTIME_ROOT}/src/system/gesture/CameraInput.cpp
    ${DC3_RUNTIME_ROOT}/src/system/gesture/CameraTilt.cpp
    ${DC3_RUNTIME_ROOT}/src/system/gesture/DepthBuffer3D.cpp
    ${DC3_RUNTIME_ROOT}/src/system/gesture/DirectionGestureFilter.cpp
    ${DC3_RUNTIME_ROOT}/src/system/gesture/DrawUtl.cpp
    ${DC3_RUNTIME_ROOT}/src/system/gesture/FitnessFilter.cpp
    ${DC3_RUNTIME_ROOT}/src/system/gesture/FreestyleMotionFilter.cpp
    ${DC3_RUNTIME_ROOT}/src/system/gesture/Gesture.cpp
    ${DC3_RUNTIME_ROOT}/src/system/gesture/GestureMgr.cpp
    ${DC3_RUNTIME_ROOT}/src/system/gesture/HandHeightGestureFilter.cpp
    ${DC3_RUNTIME_ROOT}/src/system/gesture/HandInvokeGestureFilter.cpp
    ${DC3_RUNTIME_ROOT}/src/system/gesture/HandRaisedGestureFilter.cpp
    ${DC3_RUNTIME_ROOT}/src/system/gesture/HandsUpGestureFilter.cpp
    ${DC3_RUNTIME_ROOT}/src/system/gesture/HighFiveGestureFilter.cpp
    ${DC3_RUNTIME_ROOT}/src/system/gesture/IdentityInfo.cpp
    ${DC3_RUNTIME_ROOT}/src/system/gesture/JointUtl.cpp
    ${DC3_RUNTIME_ROOT}/src/system/gesture/LiveCameraInput.cpp
    ${DC3_RUNTIME_ROOT}/src/system/gesture/NavigationSkeletonDir.cpp
    ${DC3_RUNTIME_ROOT}/src/system/gesture/SkeletonClip.cpp
    ${DC3_RUNTIME_ROOT}/src/system/gesture/Skeleton.cpp
    ${DC3_RUNTIME_ROOT}/src/system/gesture/SkeletonDir.cpp
    ${DC3_RUNTIME_ROOT}/src/system/gesture/SkeletonExtentTracker.cpp
    ${DC3_RUNTIME_ROOT}/src/system/gesture/SkeletonHistory.cpp
    ${DC3_RUNTIME_ROOT}/src/system/gesture/SkeletonQualityFilter.cpp
    ${DC3_RUNTIME_ROOT}/src/system/gesture/SkeletonRecoverer.cpp
    ${DC3_RUNTIME_ROOT}/src/system/gesture/SkeletonUpdate.cpp
    ${DC3_RUNTIME_ROOT}/src/system/gesture/SkeletonViz.cpp
    ${DC3_RUNTIME_ROOT}/src/system/gesture/SpeechMgr.cpp
    ${DC3_RUNTIME_ROOT}/src/system/gesture/StandingStillGestureFilter.cpp
    ${DC3_RUNTIME_ROOT}/src/system/gesture/StreamRecorder.cpp
    ${DC3_RUNTIME_ROOT}/src/system/gesture/StreamRenderer.cpp
    ${DC3_RUNTIME_ROOT}/src/system/gesture/StubCameraInput.cpp
    ${DC3_RUNTIME_ROOT}/src/system/gesture/WaveToTurnOnLight.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/BustAMoveData.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/CamShotCatVO.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/CharCameraInput.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/CharFeedback.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/ClipPlayer.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/CrazeHollaback.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/DanceRemixer.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/DancerSequence.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/DancerSkeleton.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/DetectFrame.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/Difficulty.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/ErrorNode.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/FilterQueue.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/FilterVersion.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/FreestyleMove.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/FreestyleMoveRecorder.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/HamAudio.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/HamBattleData.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/HamCamShot.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/HamCamTransform.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/HamCharacter.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/Ham.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/HamDirector.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/HamDriver.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/HamGameData.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/HamIconMan.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/HamIKEffector.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/HamIKSkeleton.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/HamLabel.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/HamList.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/HamListRibbon.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/HamMaster.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/HamMove.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/HamNavList.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/HamNavProvider.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/HamPartyJumpData.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/HamPhotoDisplay.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/HamPhraseMeter.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/HamPlayerData.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/HamProviderPrinter.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/HamRegulate.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/HamRibbon.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/HamScrollBehavior.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/HamScrollSpeedIndicator.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/HamSkeletonConverter.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/HamSong.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/HamSongData.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/HamSupereasyData.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/HamVisDir.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/HamWardrobe.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/HollaBackMinigame.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/MeterDisplay.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/MiniGameMgr.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/MiniLeaderboardDisplay.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/MocapSkeletonIterator.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/MoveAsyncDetector.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/MoveDir.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/MoveGraph.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/MoveMgr.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/MoveParent.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/MoveVariant.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/OriginalChoreoRemixer.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/PhotoSpotlightPositioner.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/Pose.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/PoseFatalities.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/PracticeOptionsProvider.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/PracticeSection.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/RhythmBattle.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/RhythmBattlePlayer.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/RhythmDetector.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/RhythmDetectorGroup.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/ScoreUtl.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/SongCollision.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/SongDifficultyDisplay.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/SongLayout.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/SongUtl.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/StarsDisplay.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/SuperEasyRemixer.cpp
    ${DC3_RUNTIME_ROOT}/src/system/hamobj/TransConstraint.cpp
    ${DC3_RUNTIME_ROOT}/src/system/jpeg/Jpeg.cpp
    ${DC3_RUNTIME_ROOT}/src/system/math/Color.cpp
    ${DC3_RUNTIME_ROOT}/src/system/math/Decibels.cpp
    ${DC3_RUNTIME_ROOT}/src/system/math/DoubleExponentialSmoother.cpp
    ${DC3_RUNTIME_ROOT}/src/system/math/Easing.cpp
    ${DC3_RUNTIME_ROOT}/src/system/math/FileChecksum.cpp
    ${DC3_RUNTIME_ROOT}/src/system/math/Geo.cpp
    ${DC3_RUNTIME_ROOT}/src/system/math/Interp.cpp
    ${DC3_RUNTIME_ROOT}/src/system/math/Key.cpp
    ${DC3_RUNTIME_ROOT}/src/system/math/mtx.cpp
    ${DC3_RUNTIME_ROOT}/src/system/math/Primes.cpp
    ${DC3_RUNTIME_ROOT}/src/system/math/Rand2.cpp
    ${DC3_RUNTIME_ROOT}/src/system/math/Rand.cpp
    ${DC3_RUNTIME_ROOT}/src/system/math/Rot.cpp
    ${DC3_RUNTIME_ROOT}/src/system/math/SHA1.cpp
    ${DC3_RUNTIME_ROOT}/src/system/math/Sort.cpp
    ${DC3_RUNTIME_ROOT}/src/system/math/StreamChecksum.cpp
    ${DC3_RUNTIME_ROOT}/src/system/math/Trig.cpp
    ${DC3_RUNTIME_ROOT}/src/system/math/vec.cpp
    ${DC3_RUNTIME_ROOT}/src/system/meta/Achievements.cpp
    ${DC3_RUNTIME_ROOT}/src/system/meta/ButtonHolder.cpp
    ${DC3_RUNTIME_ROOT}/src/system/meta/ConnectionStatusPanel.cpp
    ${DC3_RUNTIME_ROOT}/src/system/meta/CreditsPanel.cpp
    ${DC3_RUNTIME_ROOT}/src/system/meta/DataArraySongInfo.cpp
    ${DC3_RUNTIME_ROOT}/src/system/meta/DeJitterPanel.cpp
    ${DC3_RUNTIME_ROOT}/src/system/meta/FixedSizeSaveable.cpp
    ${DC3_RUNTIME_ROOT}/src/system/meta/FixedSizeSaveableStream.cpp
    ${DC3_RUNTIME_ROOT}/src/system/meta/HAQManager.cpp
    ${DC3_RUNTIME_ROOT}/src/system/meta/HeldButtonPanel.cpp
    ${DC3_RUNTIME_ROOT}/src/system/meta/Jukebox.cpp
    ${DC3_RUNTIME_ROOT}/src/system/meta/MemcardAction.cpp
    ${DC3_RUNTIME_ROOT}/src/system/meta/MemcardMgr.cpp
    ${DC3_RUNTIME_ROOT}/src/system/meta/Meta.cpp
    ${DC3_RUNTIME_ROOT}/src/system/meta/MetaMusicManager.cpp
    ${DC3_RUNTIME_ROOT}/src/system/meta/MetaMusicScene.cpp
    ${DC3_RUNTIME_ROOT}/src/system/meta/MoviePanel.cpp
    ${DC3_RUNTIME_ROOT}/src/system/meta/PreloadPanel.cpp
    ${DC3_RUNTIME_ROOT}/src/system/meta/Profile.cpp
    ${DC3_RUNTIME_ROOT}/src/system/meta/SongMetadata.cpp
    ${DC3_RUNTIME_ROOT}/src/system/meta/SongMgr.cpp
    ${DC3_RUNTIME_ROOT}/src/system/meta/SongPreview.cpp
    ${DC3_RUNTIME_ROOT}/src/system/meta/Sorting.cpp
    ${DC3_RUNTIME_ROOT}/src/system/meta/StoreEnumeration.cpp
    ${DC3_RUNTIME_ROOT}/src/system/meta/StoreOffer.cpp
    ${DC3_RUNTIME_ROOT}/src/system/meta/StorePanel.cpp
    ${DC3_RUNTIME_ROOT}/src/system/meta/StorePreviewMgr.cpp
    ${DC3_RUNTIME_ROOT}/src/system/meta/StorePurchaser.cpp
    ${DC3_RUNTIME_ROOT}/src/system/meta/StreamPlayer.cpp
    ${DC3_RUNTIME_ROOT}/src/system/midi/DataEventList.cpp
    ${DC3_RUNTIME_ROOT}/src/system/midi/DisplayEvents.cpp
    ${DC3_RUNTIME_ROOT}/src/system/midi/MidiParser.cpp
    ${DC3_RUNTIME_ROOT}/src/system/midi/MidiParserMgr.cpp
    ${DC3_RUNTIME_ROOT}/src/system/midi/MidiReader.cpp
    ${DC3_RUNTIME_ROOT}/src/system/midi/MidiReceiver.cpp
    ${DC3_RUNTIME_ROOT}/src/system/midi/MidiVarLen.cpp
    ${DC3_RUNTIME_ROOT}/src/system/moviebink/BinkMovieImpl.cpp
    ${DC3_RUNTIME_ROOT}/src/system/moviebink/BinkMovieSys.cpp
    ${DC3_RUNTIME_ROOT}/src/system/movie/Movie.cpp
    ${DC3_RUNTIME_ROOT}/src/system/movie/MovieImpl.cpp
    ${DC3_RUNTIME_ROOT}/src/system/movie/MovieSys.cpp
    ${DC3_RUNTIME_ROOT}/src/system/movie/Splash.cpp
    ${DC3_RUNTIME_ROOT}/src/system/movie/TexMovie.cpp
    ${DC3_RUNTIME_ROOT}/src/system/net/DingoAuthJob.cpp
    ${DC3_RUNTIME_ROOT}/src/system/net/DingoJob.cpp
    ${DC3_RUNTIME_ROOT}/src/system/net/DingoSvr.cpp
    ${DC3_RUNTIME_ROOT}/src/system/net/HttpGet.cpp
    ${DC3_RUNTIME_ROOT}/src/system/net/HttpReq.cpp
    ${DC3_RUNTIME_ROOT}/src/system/net/HttpReqCurl.cpp
    ${DC3_RUNTIME_ROOT}/src/system/net/JsonMemory.cpp
    ${DC3_RUNTIME_ROOT}/src/system/net/JsonUtils.cpp
    ${DC3_RUNTIME_ROOT}/src/system/net/WebSvcMgr.cpp
    ${DC3_RUNTIME_ROOT}/src/system/net/WebSvcMgrCurl.cpp
    ${DC3_RUNTIME_ROOT}/src/system/net/WebSvcReq.cpp
    ${DC3_RUNTIME_ROOT}/src/system/net/XLSPConnection.cpp
    ${DC3_RUNTIME_ROOT}/src/system/obj/DataArray.cpp
    ${DC3_RUNTIME_ROOT}/src/system/obj/DataFile.cpp
    ${DC3_RUNTIME_ROOT}/src/system/obj/DataFlex.c
    ${DC3_RUNTIME_ROOT}/src/system/obj/DataFunc.cpp
    ${DC3_RUNTIME_ROOT}/src/system/obj/DataNode.cpp
    ${DC3_RUNTIME_ROOT}/src/system/obj/DataUtl.cpp
    ${DC3_RUNTIME_ROOT}/src/system/obj/Dir.cpp
    ${DC3_RUNTIME_ROOT}/src/system/obj/DirLoader.cpp
    ${DC3_RUNTIME_ROOT}/src/system/obj/DirUnloader.cpp
    ${DC3_RUNTIME_ROOT}/src/system/obj/MessageTimer.cpp
    ${DC3_RUNTIME_ROOT}/src/system/obj/Msg.cpp
    ${DC3_RUNTIME_ROOT}/src/system/obj/Object.cpp
    ${DC3_RUNTIME_ROOT}/src/system/obj/PropSync.cpp
    ${DC3_RUNTIME_ROOT}/src/system/obj/Task.cpp
    ${DC3_RUNTIME_ROOT}/src/system/obj/TextFile.cpp
    ${DC3_RUNTIME_ROOT}/src/system/obj/TypeProps.cpp
    ${DC3_RUNTIME_ROOT}/src/system/obj/Utl.cpp
    ${DC3_RUNTIME_ROOT}/src/system/oggvorbis/bitwise.c
    ${DC3_RUNTIME_ROOT}/src/system/oggvorbis/framing.c
    ${DC3_RUNTIME_ROOT}/src/system/oggvorbis/VorbisMem.cpp
    ${DC3_RUNTIME_ROOT}/src/system/os/AppChild.cpp
    ${DC3_RUNTIME_ROOT}/src/system/os/Archive.cpp
    ${DC3_RUNTIME_ROOT}/src/system/os/ArkFile.cpp
    ${DC3_RUNTIME_ROOT}/src/system/os/AsyncFile.cpp
    ${DC3_RUNTIME_ROOT}/src/system/os/AsyncFileHolmes.cpp
    ${DC3_RUNTIME_ROOT}/src/system/os/AsyncTask.cpp
    ${DC3_RUNTIME_ROOT}/src/system/os/BlockMgr.cpp
    ${DC3_RUNTIME_ROOT}/src/system/os/ContentMgr.cpp
    ${DC3_RUNTIME_ROOT}/src/system/os/CritSec.cpp
    ${DC3_RUNTIME_ROOT}/src/system/os/DateTime.cpp
    ${DC3_RUNTIME_ROOT}/src/system/os/Debug.cpp
    ${DC3_RUNTIME_ROOT}/src/system/os/FileCache.cpp
    ${DC3_RUNTIME_ROOT}/src/system/os/File.cpp
    ${DC3_RUNTIME_ROOT}/src/system/os/HDCache.cpp
    ${DC3_RUNTIME_ROOT}/src/system/os/HolmesClient.cpp
    ${DC3_RUNTIME_ROOT}/src/system/os/HolmesClient_NetSocket.cpp
    ${DC3_RUNTIME_ROOT}/src/system/os/HolmesKeyboard.cpp
    ${DC3_RUNTIME_ROOT}/src/system/os/HolmesUtl.cpp
    ${DC3_RUNTIME_ROOT}/src/system/os/JoypadClient.cpp
    ${DC3_RUNTIME_ROOT}/src/system/os/Joypad.cpp
    ${DC3_RUNTIME_ROOT}/src/system/os/JoypadMsgs.cpp
    ${DC3_RUNTIME_ROOT}/src/system/os/Joypad_Xinput.cpp
    ${DC3_RUNTIME_ROOT}/src/system/os/Keyboard.cpp
    ${DC3_RUNTIME_ROOT}/src/system/os/KeyboardJoypadAdapter.cpp
    ${DC3_RUNTIME_ROOT}/src/system/os/Memcard.cpp
    ${DC3_RUNTIME_ROOT}/src/system/os/NetStream.cpp
    ${DC3_RUNTIME_ROOT}/src/system/os/NetworkSocket.cpp
    ${DC3_RUNTIME_ROOT}/src/system/os/OnlineID.cpp
    ${DC3_RUNTIME_ROOT}/src/system/os/PlatformMgr.cpp
    ${DC3_RUNTIME_ROOT}/src/system/os/SynchronizationEvent.cpp
    ${DC3_RUNTIME_ROOT}/src/system/os/System.cpp
    ${DC3_RUNTIME_ROOT}/src/system/os/Timer.cpp
    ${DC3_RUNTIME_ROOT}/src/system/os/UsbMidiGuitar.cpp
    ${DC3_RUNTIME_ROOT}/src/system/os/UsbMidiGuitarMsgs.cpp
    ${DC3_RUNTIME_ROOT}/src/system/os/UsbMidiKeyboard.cpp
    ${DC3_RUNTIME_ROOT}/src/system/os/UsbMidiKeyboardMsgs.cpp
    ${DC3_RUNTIME_ROOT}/src/system/os/User.cpp
    ${DC3_RUNTIME_ROOT}/src/system/os/UserMgr.cpp
    ${DC3_RUNTIME_ROOT}/src/system/os/VirtualKeyboard.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/AmbientOcclusion.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/Anim.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/AnimFilter.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/BaseMaterial.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/Bitmap.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/BoxMap.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/CamAnim.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/Cam.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/ColorXfm.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/Console.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/CubeTex.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/Dir.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/DOFProc.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/DOFProc_NG.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/Draw.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/Enter.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/Env.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/Env_NG.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/EventTrigger.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/Flare.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/Font3d.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/FontBase.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/Font.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/Fur.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/Fur_NG.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/Gen.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/Graph.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/Group.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/HiResScreen.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/Line.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/LitAnim.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/Lit.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/Lit_NG.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/MatAnim.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/Mat.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/Mat_NG.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/MeshAnim.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/Mesh.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/MeshDeform.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/MetaMaterial.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/Morph.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/MotionBlur.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/Movie.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/MultiMesh.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/MultiMeshProxy.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/Overlay.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/PartAnim.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/Part.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/PartLauncher.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/PollAnim.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/Poll.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/PostProc.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/PostProcMgr.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/PostProc_NG.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/PropAnim.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/PropKeys.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/Ribbon.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/Rnd.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/Rnd_NG.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/ScreenMask.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/Set.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/Shader.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/ShaderMgr.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/ShaderOptions.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/ShaderProgram.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/ShadowMap.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/Shockwave.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/SIVideo.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/SoftParticleBuffer.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/SoftParticles.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/Spline.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/TexBlendController.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/TexBlender.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/Tex.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/TexProc.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/TexRenderer.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/Text.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/TransAnim.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/Trans.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/TransProxy.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/Utl.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/VelocityBuffer.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/Watcher.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/Wind.cpp
    ${DC3_RUNTIME_ROOT}/src/system/rndobj/wordwrap.cpp
    ${DC3_RUNTIME_ROOT}/src/system/synth/ADSR.cpp
    ${DC3_RUNTIME_ROOT}/src/system/synth/AudioDucker.cpp
    ${DC3_RUNTIME_ROOT}/src/system/synth/BinkReader.cpp
    ${DC3_RUNTIME_ROOT}/src/system/synth/BitCrushEffect.cpp
    ${DC3_RUNTIME_ROOT}/src/system/synth/ByteGrinder.cpp
    ${DC3_RUNTIME_ROOT}/src/system/synth/complex.cpp
    ${DC3_RUNTIME_ROOT}/src/system/synth/CompressionEffect.cpp
    ${DC3_RUNTIME_ROOT}/src/system/synth/DelayEffect.cpp
    ${DC3_RUNTIME_ROOT}/src/system/synth/DistortionEffect.cpp
    ${DC3_RUNTIME_ROOT}/src/system/synth/Emitter.cpp
    ${DC3_RUNTIME_ROOT}/src/system/synth/EQEffect.cpp
    ${DC3_RUNTIME_ROOT}/src/system/synth/Faders.cpp
    ${DC3_RUNTIME_ROOT}/src/system/synth/filterdesign.cpp
    ${DC3_RUNTIME_ROOT}/src/system/synth/FlangerEffect.cpp
    ${DC3_RUNTIME_ROOT}/src/system/synth/FxSendBitCrush.cpp
    ${DC3_RUNTIME_ROOT}/src/system/synth/FxSendChorus.cpp
    ${DC3_RUNTIME_ROOT}/src/system/synth/FxSendCompress.cpp
    ${DC3_RUNTIME_ROOT}/src/system/synth/FxSend.cpp
    ${DC3_RUNTIME_ROOT}/src/system/synth/FxSendDelay.cpp
    ${DC3_RUNTIME_ROOT}/src/system/synth/FxSendDistortion.cpp
    ${DC3_RUNTIME_ROOT}/src/system/synth/FxSendEQ.cpp
    ${DC3_RUNTIME_ROOT}/src/system/synth/FxSendFlanger.cpp
    ${DC3_RUNTIME_ROOT}/src/system/synth/FxSendMeterEffect.cpp
    ${DC3_RUNTIME_ROOT}/src/system/synth/FxSendPitchShift.cpp
    ${DC3_RUNTIME_ROOT}/src/system/synth/FxSendReverb.cpp
    ${DC3_RUNTIME_ROOT}/src/system/synth/FxSendSynapse.cpp
    ${DC3_RUNTIME_ROOT}/src/system/synth/FxSendWah.cpp
    ${DC3_RUNTIME_ROOT}/src/system/synth/MetaMusic.cpp
    ${DC3_RUNTIME_ROOT}/src/system/synth/MeterEffectMonitor.cpp
    ${DC3_RUNTIME_ROOT}/src/system/synth/MicClientMapper.cpp
    ${DC3_RUNTIME_ROOT}/src/system/synth/Mic.cpp
    ${DC3_RUNTIME_ROOT}/src/system/synth/MicNull.cpp
    ${DC3_RUNTIME_ROOT}/src/system/synth/MidiChannel.cpp
    ${DC3_RUNTIME_ROOT}/src/system/synth/MidiInstrument.cpp
    ${DC3_RUNTIME_ROOT}/src/system/synth/MidiSynth.cpp
    ${DC3_RUNTIME_ROOT}/src/system/synth/MoggClip.cpp
    ${DC3_RUNTIME_ROOT}/src/system/synth/MoggClipMap.cpp
    ${DC3_RUNTIME_ROOT}/src/system/synth/OggMap.cpp
    ${DC3_RUNTIME_ROOT}/src/system/synth/Pollable.cpp
    ${DC3_RUNTIME_ROOT}/src/system/synth/SampleData.cpp
    ${DC3_RUNTIME_ROOT}/src/system/synth/SampleInst.cpp
    ${DC3_RUNTIME_ROOT}/src/system/synth/SampleZone.cpp
    ${DC3_RUNTIME_ROOT}/src/system/synth/Sequence.cpp
    ${DC3_RUNTIME_ROOT}/src/system/synth/Sfx.cpp
    ${DC3_RUNTIME_ROOT}/src/system/synth/SfxMap.cpp
    ${DC3_RUNTIME_ROOT}/src/system/synth/Sound.cpp
    ${DC3_RUNTIME_ROOT}/src/system/synth/StandardStream.cpp
    ${DC3_RUNTIME_ROOT}/src/system/synth/Stream.cpp
    ${DC3_RUNTIME_ROOT}/src/system/synth/StreamNull.cpp
    ${DC3_RUNTIME_ROOT}/src/system/synth/StreamReceiver.cpp
    ${DC3_RUNTIME_ROOT}/src/system/synth/StreamReceiverFile.cpp
    ${DC3_RUNTIME_ROOT}/src/system/synth/Synth.cpp
    ${DC3_RUNTIME_ROOT}/src/system/synth/SynthSample.cpp
    ${DC3_RUNTIME_ROOT}/src/system/synth/ThreeDSound.cpp
    ${DC3_RUNTIME_ROOT}/src/system/synth/tomcrypt/aes.c
    ${DC3_RUNTIME_ROOT}/src/system/synth/tomcrypt/crypt.c
    ${DC3_RUNTIME_ROOT}/src/system/synth/tomcrypt/ctr.c
    ${DC3_RUNTIME_ROOT}/src/system/synth/tomcrypt/TomCryptLicense.cpp
    ${DC3_RUNTIME_ROOT}/src/system/synth/Utl.cpp
    ${DC3_RUNTIME_ROOT}/src/system/synth/VorbisReader.cpp
    ${DC3_RUNTIME_ROOT}/src/system/synth/WahEffect.cpp
    ${DC3_RUNTIME_ROOT}/src/system/synth/WavMgr.cpp
    ${DC3_RUNTIME_ROOT}/src/system/synth/WavReader.cpp
    ${DC3_RUNTIME_ROOT}/src/system/ui/CheatProvider.cpp
    ${DC3_RUNTIME_ROOT}/src/system/ui/InlineHelp.cpp
    ${DC3_RUNTIME_ROOT}/src/system/ui/LabelNumberTicker.cpp
    ${DC3_RUNTIME_ROOT}/src/system/ui/LabelShrinkWrapper.cpp
    ${DC3_RUNTIME_ROOT}/src/system/ui/LocalePanel.cpp
    ${DC3_RUNTIME_ROOT}/src/system/ui/PanelDir.cpp
    ${DC3_RUNTIME_ROOT}/src/system/ui/ResourceDirPtr.cpp
    ${DC3_RUNTIME_ROOT}/src/system/ui/Screenshot.cpp
    ${DC3_RUNTIME_ROOT}/src/system/ui/ScrollSelect.cpp
    ${DC3_RUNTIME_ROOT}/src/system/ui/UIButton.cpp
    ${DC3_RUNTIME_ROOT}/src/system/ui/UIColor.cpp
    ${DC3_RUNTIME_ROOT}/src/system/ui/UIComponent.cpp
    ${DC3_RUNTIME_ROOT}/src/system/ui/UI.cpp
    ${DC3_RUNTIME_ROOT}/src/system/ui/UIFontImporter.cpp
    ${DC3_RUNTIME_ROOT}/src/system/ui/UIGuide.cpp
    ${DC3_RUNTIME_ROOT}/src/system/ui/UILabel.cpp
    ${DC3_RUNTIME_ROOT}/src/system/ui/UILabelDir.cpp
    ${DC3_RUNTIME_ROOT}/src/system/ui/UIListArrow.cpp
    ${DC3_RUNTIME_ROOT}/src/system/ui/UIList.cpp
    ${DC3_RUNTIME_ROOT}/src/system/ui/UIListCustom.cpp
    ${DC3_RUNTIME_ROOT}/src/system/ui/UIListDir.cpp
    ${DC3_RUNTIME_ROOT}/src/system/ui/UIListHighlight.cpp
    ${DC3_RUNTIME_ROOT}/src/system/ui/UIListLabel.cpp
    ${DC3_RUNTIME_ROOT}/src/system/ui/UIListMesh.cpp
    ${DC3_RUNTIME_ROOT}/src/system/ui/UIListProvider.cpp
    ${DC3_RUNTIME_ROOT}/src/system/ui/UIListSlot.cpp
    ${DC3_RUNTIME_ROOT}/src/system/ui/UIListState.cpp
    ${DC3_RUNTIME_ROOT}/src/system/ui/UIListSubList.cpp
    ${DC3_RUNTIME_ROOT}/src/system/ui/UIListWidget.cpp
    ${DC3_RUNTIME_ROOT}/src/system/ui/UIPanel.cpp
    ${DC3_RUNTIME_ROOT}/src/system/ui/UIPicture.cpp
    ${DC3_RUNTIME_ROOT}/src/system/ui/UIScreen.cpp
    ${DC3_RUNTIME_ROOT}/src/system/ui/UISlider.cpp
    ${DC3_RUNTIME_ROOT}/src/system/ui/UITransitionHandler.cpp
    ${DC3_RUNTIME_ROOT}/src/system/ui/UITrigger.cpp
    ${DC3_RUNTIME_ROOT}/src/system/ui/Utl.cpp
    ${DC3_RUNTIME_ROOT}/src/system/utl/AllocInfo.cpp
    ${DC3_RUNTIME_ROOT}/src/system/utl/BeatMap.cpp
    ${DC3_RUNTIME_ROOT}/src/system/utl/BinkIntegration.cpp
    ${DC3_RUNTIME_ROOT}/src/system/utl/BinStream.cpp
    ${DC3_RUNTIME_ROOT}/src/system/utl/BufStream.cpp
    ${DC3_RUNTIME_ROOT}/src/system/utl/Cache.cpp
    ${DC3_RUNTIME_ROOT}/src/system/utl/CacheMgr.cpp
    ${DC3_RUNTIME_ROOT}/src/system/utl/Cheats.cpp
    ${DC3_RUNTIME_ROOT}/src/system/utl/ChunkIDs.cpp
    ${DC3_RUNTIME_ROOT}/src/system/utl/Chunks.cpp
    ${DC3_RUNTIME_ROOT}/src/system/utl/ChunkStream.cpp
    ${DC3_RUNTIME_ROOT}/src/system/utl/Compress.cpp
    ${DC3_RUNTIME_ROOT}/src/system/utl/Crc.cpp
    ${DC3_RUNTIME_ROOT}/src/system/utl/DataPointMgr.cpp
    ${DC3_RUNTIME_ROOT}/src/system/utl/DebugGraph.cpp
    ${DC3_RUNTIME_ROOT}/src/system/utl/DebugMeter.cpp
    ${DC3_RUNTIME_ROOT}/src/system/utl/DeJitter.cpp
    ${DC3_RUNTIME_ROOT}/src/system/utl/EncryptXTEA.cpp
    ${DC3_RUNTIME_ROOT}/src/system/utl/FakeSongMgr.cpp
    ${DC3_RUNTIME_ROOT}/src/system/utl/FilePath.cpp
    ${DC3_RUNTIME_ROOT}/src/system/utl/FileStream.cpp
    ${DC3_RUNTIME_ROOT}/src/system/utl/GlitchFinder.cpp
    ${DC3_RUNTIME_ROOT}/src/system/utl/HxGuid.cpp
    ${DC3_RUNTIME_ROOT}/src/system/utl/JobMgr.cpp
    ${DC3_RUNTIME_ROOT}/src/system/utl/JsonEncode.cpp
    ${DC3_RUNTIME_ROOT}/src/system/utl/KnownIssues.cpp
    ${DC3_RUNTIME_ROOT}/src/system/utl/Licenses.cpp
    ${DC3_RUNTIME_ROOT}/src/system/utl/Loader.cpp
    ${DC3_RUNTIME_ROOT}/src/system/utl/Locale.cpp
    ${DC3_RUNTIME_ROOT}/src/system/utl/LocaleOrdinal.cpp
    ${DC3_RUNTIME_ROOT}/src/system/utl/Magnu.cpp
    ${DC3_RUNTIME_ROOT}/src/system/utl/MakeString.cpp
    ${DC3_RUNTIME_ROOT}/src/system/utl/MBT.cpp
    ${DC3_RUNTIME_ROOT}/src/system/utl/MeasureMap.cpp
    ${DC3_RUNTIME_ROOT}/src/system/utl/MemHeap.cpp
    ${DC3_RUNTIME_ROOT}/src/system/utl/MemMgr.cpp
    ${DC3_RUNTIME_ROOT}/src/system/utl/MemPoint.cpp
    ${DC3_RUNTIME_ROOT}/src/system/utl/MemStats.cpp
    ${DC3_RUNTIME_ROOT}/src/system/utl/MemStream.cpp
    ${DC3_RUNTIME_ROOT}/src/system/utl/MemTrack.cpp
    ${DC3_RUNTIME_ROOT}/src/system/utl/MemTracker.cpp
    ${DC3_RUNTIME_ROOT}/src/system/utl/MultiTempoTempoMap.cpp
    ${DC3_RUNTIME_ROOT}/src/system/utl/NetCacheLoader.cpp
    ${DC3_RUNTIME_ROOT}/src/system/utl/NetCacheMgr.cpp
    ${DC3_RUNTIME_ROOT}/src/system/utl/NetLoader.cpp
    ${DC3_RUNTIME_ROOT}/src/system/utl/Option.cpp
    ${DC3_RUNTIME_ROOT}/src/system/utl/OSCMessenger.cpp
    ${DC3_RUNTIME_ROOT}/src/system/utl/PoolAlloc.cpp
    ${DC3_RUNTIME_ROOT}/src/system/utl/Pool.cpp
    ${DC3_RUNTIME_ROOT}/src/system/utl/Profiler.cpp
    ${DC3_RUNTIME_ROOT}/src/system/utl/Song.cpp
    ${DC3_RUNTIME_ROOT}/src/system/utl/SongInfoAudioType.cpp
    ${DC3_RUNTIME_ROOT}/src/system/utl/SongInfoCopy.cpp
    ${DC3_RUNTIME_ROOT}/src/system/utl/Spew.cpp
    ${DC3_RUNTIME_ROOT}/src/system/utl/Str.cpp
    ${DC3_RUNTIME_ROOT}/src/system/utl/StringTable.cpp
    ${DC3_RUNTIME_ROOT}/src/system/utl/SuperFormatString.cpp
    ${DC3_RUNTIME_ROOT}/src/system/utl/Symbol.cpp
    ${DC3_RUNTIME_ROOT}/src/system/utl/TempoMap.cpp
    ${DC3_RUNTIME_ROOT}/src/system/utl/TextFileStream.cpp
    ${DC3_RUNTIME_ROOT}/src/system/utl/TextStream.cpp
    ${DC3_RUNTIME_ROOT}/src/system/utl/TimeConversion.cpp
    ${DC3_RUNTIME_ROOT}/src/system/utl/trie.cpp
    ${DC3_RUNTIME_ROOT}/src/system/utl/UrlEncode.cpp
    ${DC3_RUNTIME_ROOT}/src/system/utl/UTF8.cpp
    ${DC3_RUNTIME_ROOT}/src/system/utl/VarTimer.cpp
    ${DC3_RUNTIME_ROOT}/src/system/utl/WaveFile.cpp
    ${DC3_RUNTIME_ROOT}/src/system/world/BeatClock.cpp
    ${DC3_RUNTIME_ROOT}/src/system/world/CameraManager.cpp
    ${DC3_RUNTIME_ROOT}/src/system/world/CameraShot.cpp
    ${DC3_RUNTIME_ROOT}/src/system/world/ColorPalette.cpp
    ${DC3_RUNTIME_ROOT}/src/system/world/Crowd3DCharHandle.cpp
    ${DC3_RUNTIME_ROOT}/src/system/world/Crowd.cpp
    ${DC3_RUNTIME_ROOT}/src/system/world/DefaultPhysicsManager.cpp
    ${DC3_RUNTIME_ROOT}/src/system/world/Dir.cpp
    ${DC3_RUNTIME_ROOT}/src/system/world/FreeCamera.cpp
    ${DC3_RUNTIME_ROOT}/src/system/world/Instance.cpp
    ${DC3_RUNTIME_ROOT}/src/system/world/LightHue.cpp
    ${DC3_RUNTIME_ROOT}/src/system/world/LightPreset.cpp
    ${DC3_RUNTIME_ROOT}/src/system/world/LightPresetManager.cpp
    ${DC3_RUNTIME_ROOT}/src/system/world/PhysicsManager.cpp
    ${DC3_RUNTIME_ROOT}/src/system/world/PhysicsVolume.cpp
    ${DC3_RUNTIME_ROOT}/src/system/world/PostProcer.cpp
    ${DC3_RUNTIME_ROOT}/src/system/world/Reflection.cpp
    ${DC3_RUNTIME_ROOT}/src/system/world/Spotlight.cpp
    ${DC3_RUNTIME_ROOT}/src/system/world/SpotlightDrawer.cpp
    ${DC3_RUNTIME_ROOT}/src/system/world/SpotlightDrawer_NG.cpp
    ${DC3_RUNTIME_ROOT}/src/system/world/SpotlightEnder.cpp
    ${DC3_RUNTIME_ROOT}/src/system/world/ThreeDSoundManager.cpp
    ${DC3_RUNTIME_ROOT}/src/system/world/World.cpp
    ${DC3_RUNTIME_ROOT}/native/src/engine_stubs_generated.cpp
    ${DC3_RUNTIME_ROOT}/native/src/native_job_stubs.cpp
    ${DC3_RUNTIME_ROOT}/native/src/native_link_glue.cpp
    ${DC3_RUNTIME_ROOT}/native/src/platform/Achievements_Stub.cpp
    ${DC3_RUNTIME_ROOT}/native/src/platform/ContentMgr_Stub.cpp
    ${DC3_RUNTIME_ROOT}/native/src/platform/DingoSvr_Native.cpp
    ${DC3_RUNTIME_ROOT}/native/src/platform/FFmpegAudioReader.cpp
    ${DC3_RUNTIME_ROOT}/native/src/platform/FFmpegMovieImpl.cpp
    ${DC3_RUNTIME_ROOT}/native/src/platform/GestureMgr_Native.cpp
    ${DC3_RUNTIME_ROOT}/native/src/platform/HttpServer.cpp
    ${DC3_RUNTIME_ROOT}/native/src/platform/KinectShare_Stub.cpp
    ${DC3_RUNTIME_ROOT}/native/src/platform/MemcardMgr_Stub.cpp
    ${DC3_RUNTIME_ROOT}/native/src/platform/Memcard_Stub.cpp
    ${DC3_RUNTIME_ROOT}/native/src/platform/Memory_Native.cpp
    ${DC3_RUNTIME_ROOT}/native/src/platform/MeshFilter.cpp
    ${DC3_RUNTIME_ROOT}/native/src/platform/NetXbox_Stub.cpp
    ${DC3_RUNTIME_ROOT}/native/src/platform/PlatformMgr_Native.cpp
    ${DC3_RUNTIME_ROOT}/native/src/platform/RenderState_Native.cpp
    ${DC3_RUNTIME_ROOT}/native/src/platform/Rnd_Wgpu.cpp
    ${DC3_RUNTIME_ROOT}/native/src/platform/Skeleton_Native.cpp
    ${DC3_RUNTIME_ROOT}/native/src/platform/SongSortMgr_Native.cpp
    ${DC3_RUNTIME_ROOT}/native/src/platform/System_Native.cpp
    ${DC3_RUNTIME_ROOT}/native/src/platform/ThreadCall_Native.cpp
    ${DC3_RUNTIME_ROOT}/native/src/platform/XmaSampleDecoder.cpp
    ${DC3_RUNTIME_ROOT}/native/src/pose/CameraCapture.cpp
    ${DC3_RUNTIME_ROOT}/native/src/pose/InternalPoseProvider.cpp
    ${DC3_RUNTIME_ROOT}/native/src/pose/PoseEstimator.cpp
    ${DC3_RUNTIME_ROOT}/native/src/pose/PoseTracker.cpp
    ${DC3_RUNTIME_ROOT}/native/src/telemetry/GameplayTelemetry.cpp
    ${DC3_RUNTIME_ROOT}/native/src/thunk_stubs.cpp
    ${DC3_RUNTIME_ROOT}/native/src/xdk_shims.cpp
)
